services:
  mongodb1:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb1
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30001"]
    restart: unless-stopped
    ports:
      - "30001:30001"
    volumes:
      - mongo-replica-1-data:/data/db

  mongodb2:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb2
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30002"]
    restart: unless-stopped
    ports:
      - "30002:30002"
    volumes:
      - mongo-replica-2-data:/data/db

  mongodb3:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb3
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30003"]
    restart: unless-stopped
    ports:
      - "30003:30003"
    volumes:
      - mongo-replica-3-data:/data/db

  rabitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: always

volumes:
  mongo-replica-1-data:
  mongo-replica-2-data:
  mongo-replica-3-data:
  rabbitmq-data:
